[tox]
toxworkdir = .toxenvs/cmsplugin-filer
envlist =
    # TODO: clean up all flake8 warning
    # flake8
    py{38,312}-dj42-cms311

[testenv]
commands =
    {envpython} --version
    - coverage erase
    coverage run test_settings.py
    - coverage report
deps=
    dj42: -rtest_requirements/django_4.2.txt
    cms311: django-cms>=3.11,<3.12
    cms41: django-cms>=4.1,<4.2

[testenv:flake8]
deps = flake8
commands = flake8
basepython = python3.8

[flake8]
ignore = E251,E128,E501
exclude = cmsplugin_filer_*/migrations/*,docs/conf.py,node_modules/*,build/*,.venv/*
max-line-length = 120
